# vim-asterisk
# [[plugins]]
# repo = 'haya14busa/vim-asterisk'
# hook_add = 'call Asterisk_add()'

[[plugins]]
repo='echasnovski/mini.nvim'
lua_add = '''
require('mini.indentscope').setup{
    draw = {
        delay = 50,
        animation = require('mini.indentscope').gen_animation.quadratic({easing = 'out', duration=20}),
    },
    symbol = '│',
}
'''

# operator argumentation
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'

# textobj argumentation
[[plugins]]
repo = 'kana/vim-textobj-user'
hook_add = 'call Textobjuser_add()'
[[plugins]]
repo = 'kana/vim-textobj-syntax'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'kana/vim-textobj-entire'
hook_add = 'call Textobjentire_add()'

# move words
[[plugins]]
repo = 'woodyZootopia/jpmoveword.vim'
hook_add = '''
let g:jpmoveword_separator='，．、。・「」『』（）【】\\'
let g:matchpairs_textobject=1
let g:jpmoveword_stop_eol=2
'''

# colorscheme
[[plugins]]
repo = 'woodyZootopia/iceberg.vim'
[[plugins]]
repo = 'cocopon/pgmnt.vim'
# [[plugins]]
# repo = 'cocopon/colorswatch.vim'

[[plugins]]
repo = 'woodyZootopia/gitsession.vim'
hook_add = '''
let g:gitsession_autosave = 1
let g:gitsession_tmp_dir = g:nvim_conf_dir .. '/tmp/gitsession'
'''
[[plugins]]
repo = 'lewis6991/impatient.nvim'

[[plugins]]
repo = 'https://github.com/tyru/capture.vim'

[[plugins]]
repo = 'https://github.com/subnut/nvim-ghost.nvim'
hook_post_update = '''
  call nvim_ghost#installer#install()
'''
hook_add = '''
augroup nvim_ghost_user_autocommands
  au User www.reddit.com,www.stackoverflow.com,github.com set filetype=markdown
  au User www.overleaf.com set filetype=tex
augroup END
'''

[[plugins]]
repo='https://github.com/itchyny/lightline.vim'
hook_add = '''
call Lightline_add()
'''

[[plugins]]
repo='https://github.com/heavenshell/vim-pydocstring'
hook_add = '''
let g:pydocstring_doq_path = '/home/snakamura/.local/bin/doq'
let g:pydocstring_formatter = 'numpy'
'''
