[[plugins]]
repo = 'Shougo/deoplete-clangx'
hook_source = '''
" Change clang binary path
call deoplete#custom#var('clangx', 'clang_binary', '/usr/bin/clang')

" Change clang options
call deoplete#custom#var('clangx', 'default_c_options', '')
call deoplete#custom#var('clangx', 'default_cpp_options', '')
'''
on_ft = ['c','cpp']

[[plugins]]
repo = 'zchee/deoplete-jedi'
hook_source = '''
let g:deoplete#sources#jedi#server_timeout = 20
'''
on_ft = 'python'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'vim-airline/vim-airline.git'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
source ~/.config/nvim/plugins/airline.vim
'''

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo='Shougo/deoplete-lsp'
hook_source = '''
source ~/.config/nvim/plugins/deoplete-lsp.vim
'''
on_event = 'InsertEnter'

[[plugins]]
repo = 'fs111/pydoc.vim'
on_ft = 'python'

