# Ultisnip and snippet list
[[plugins]]
repo = 'Sirver/ultisnips'
hook_add = '''
" Trigger configuration. You need to change this to something else than <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
" let g:UltiSnipsJumpBackwardTrigger="<c-b>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
'''
[[plugins]]
repo = 'honza/vim-snippets'

# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
hook_install = 'fzf#install()'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = 'call Fzf_add()'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'call Gitgutter_add()'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'call Fugitive_add()'

# indentline implementation in lua
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
nmap <leader>t :TagbarToggle<CR>

let g:tagbar_sort = 0
let g:tagbar_autoclose = 0
'''

[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
nnoremap U :UndotreeToggle<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'call Lightline_add()'

[[plugins]]
repo = 'jpalardy/vim-slime'
hook_add = '''
nmap <c-c><c-c> <Plug>SlimeParagraphSend
nmap <c-c><c-n> <Plug>SlimeParagraphSend}/[^\n]<CR>
nmap <c-c><c-p> <Plug>SlimeParagraphSend{?[^\n]<CR>
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
hook_add = '''
let g:asyncrun_bell = 1
let g:asyncrun_open = 8
'''

[[plugins]]
repo = 'woodyZootopia/gitsession.vim'
hook_add = '''
let g:gitsession_autosave = 1
let g:gitsession_tmp_dir = g:nvim_home_directory .. '/tmp/gitsession'
'''

# [[plugins]]
# repo = 'LeafCage/vimhelpgenerator.git'

[[plugins]]
repo = 'tversteeg/registers.nvim'

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
# [[plugins]]
# repo = 'cocopon/pgmnt.vim'
# [[plugins]]
# repo = 'cocopon/inspecthi.vim'
# [[plugins]]
# repo = 'cocopon/colorswatch.vim'

[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'
hook_post_source = '''
let g:dps_ghosttext#ftmap['www.overleaf.com']='tex'
let g:dps_ghosttext#ftmap['localhost:8888']='python'
'''

[[plugins]]
repo = 'cohama/agit.vim'
hook_add = '''
nnoremap <leader>gl <Cmd>Agit<CR>
'''
hook_post_source = '''
hi link agitStatAdded diffAdded
hi link agitStatRemoved diffRemoved
hi link agitDiffAdd diffAdded
hi link agitDiffRemove diffRemoved
'''

[[plugins]]
repo = 'voldikss/vim-floaterm.git'
hook_add = '''
let g:floaterm_width=0.9
let g:floaterm_height=0.9
nnoremap <Plug>(my-win)z <Cmd>FloatermToggle<CR>
tnoremap <silent> <C-[> <C-\><C-n>:FloatermToggle<CR>
tnoremap <silent> <C-l> <C-\><C-n>
'''

# [[plugins]]
# repo='~/ghq/github.com/woodyZootopia/novel-char-counter'
# hook_post_source='''
# augroup calc-novel-diff
#     autocmd!
#     autocmd BufReadPost,BufWritePost,InsertLeave *.txt call NCCUpdateEditDistance()
# augroup END

# '''
