[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_leader_key=','
'''
on_ft = ['html', 'xml', 'vue', 'htmldjango']
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = 'call Vimtex_add()'
[[plugins]]
repo = 'AtsushiM/search-parent.vim'
on_ft = ['sass','scss','css']
[[plugins]]
repo = 'akiyan/vim-textobj-php'
on_ft = ['html','htm']
[[plugins]]
repo = 'tpope/vim-surround'
on_ft = ['html','htm']
[[plugins]]
repo = 'wokalski/autocomplete-flow'
on_ft = ['html', 'htm', 'js']
[[plugins]]
repo = 'zeekay/vim-beautify'
on_ft = ['html', 'htm', 'js']
[[plugins]]
repo = 'AtsushiM/sass-compile.vim'
on_ft = ['sass','scss']
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_folding_disabled = 1
'''
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['lisp']

# ddc and its plugins
[[plugins]]
repo = 'Shougo/ddc.vim'
hook_post_source = 'call Ddc_add()'
on_event = 'InsertEnter'
depends = ['ddc-nvim-lsp', 'ddc-matcher_fuzzy', 'ddc-ultisnips', 'ddc-sorter_rank', 'ddc-around', 'ddc-buffer', 'ddc-file', 'ddc-dictionary']

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
[[plugins]]
repo = 'matsui54/ddc-matcher_fuzzy'
[[plugins]]
repo = 'matsui54/ddc-ultisnips'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
[[plugins]]
repo = 'Shougo/ddc-around'
[[plugins]]
repo = 'matsui54/ddc-buffer'
[[plugins]]
repo = 'LumaKernel/ddc-file'
[[plugins]]
repo = 'matsui54/ddc-dictionary'
# [[plugins]]
# repo = '~/ghq/github.com/woodyZootopia/ddc-spell-user'

[[plugins]]
repo =  'kyazdani42/nvim-tree.lua'
hook_add = '''
nmap <silent> <leader>d :<C-u>exe 'lcd' expand('%:p:h')<CR><Cmd>NvimTreeToggle<CR>
nmap <silent> [Win]t    :<C-u>tab sp<CR><leader>d
nmap <silent> <leader>n <Cmd>NvimTreeFocus<CR>
'''
hook_post_source = '''
exe 'source' expand('~/.config/nvim/toml/nvim-tree.lua')
'''
on_map = ['<Cmd>NvimTreeToggle', '<Cmd>NvimTreeFocus']

# align
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga  <Plug>(EasyAlign)
'''
on_map = '<Plug>(EasyAlign)'

# paren closing completion
[[plugins]]
repo = 'kana/vim-smartinput'
on_event = 'InsertEnter'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_ft = ['css', 'vim', 'markdown']
hook_post_source = '''
luado require 'colorizer'.setup()
ColorizerAttachToBuffer " Attach to the current buffer
'''

# LSP configuration
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_ft = ['c', 'cpp', 'rust', 'python', 'vim', 'tex', 'javascript', 'typescript']
depends = 'lsp_signature.nvim'
hook_post_source = '''
if !exists('g:vscode')
    exe 'source' g:nvim_home_directory .. 'rcs/lsp.vim'
endif
LspStart
'''
[[plugins]]
repo = 'ray-x/lsp_signature.nvim'

[[plugins]]
repo = 'tpope/vim-dispatch'
on_map = '<Cmd>Dispatch!'

[[plugins]]
repo = 'bps/vim-textobj-python'
hook_add = '''
let g:textobj_python_no_default_key_mappings = 1
'''
hook_post_source = 'call Textobjpython_postsource()'
on_ft = 'python'

# commenter
[[plugins]]
repo = 'b3nj5m1n/kommentary'
hook_add = 'call Nerdcommenter_add()'
on_map = '<Plug>kommentary'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = '0'
hook_post_source = 'call Treesitter_postsource()'
hook_install = 'TSUpdate'
hook_post_update = 'TSUpdate'
on_ft = ['c', 'cpp', 'python', 'rust', 'latex', 'vim']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript']
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'
