[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'https://github.com/neoclide/coc.nvim'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.config/nvim/plugins/defx.vim
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
source ~/.config/nvim/plugins/deol.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'Shougo/unite-outline'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/neoyank.vim'
[[plugins]]
repo = 'neoclide/denite-git'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
source ~/.config/nvim/plugins/indentline.vim
'''

[[plugins]]
repo = 'git@github.com:SirVer/ultisnips.git'
hook_add = '''
source ~/.config/nvim/plugins/ultisnip.vim
'''

[[plugins]]
repo = 'kana/vim-smartinput'
hook_add='''
source ~/.config/nvim/plugins/smartinput.vim
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'woodyZootopia/flatwhite-vim'

[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'
hook_add = '''
source ~/.config/nvim/plugins/textobj.vim
'''

[[plugins]]
repo = 'kana/vim-textobj-syntax'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'kana/vim-textobj-entire'
hook_add = '''
source ~/.config/nvim/plugins/textobj_entire.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/plugins/gitgutter-fugitive.vim
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
source ~/.config/nvim/plugins/nerdcommenter.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
source ~/.config/nvim/plugins/tabular_easyalign.vim
'''

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'majutsushi/tagbar.git'
hook_add = '''
source ~/.config/nvim/plugins/tagbar.vim
'''

[[plugins]]
repo='t9md/vim-quickhl.git'
hook_add = '''
source ~/.config/nvim/plugins/quickhl.vim
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.config/nvim/plugins/languageclient.vim
'''

[[plugins]]
repo = 'Shougo/echodoc.vim'
hook_add = '''
source ~/.config/nvim/plugins/echodoc.vim
'''

[[plugins]]
repo = 'https://github.com/qnighy/satysfi.vim'

[[plugins]]
repo = 'ncm2/float-preview.nvim.git'
hook_add = '''
source ~/.config/nvim/plugins/float-preview.vim
'''

[[plugins]]
repo = 'https://github.com/flazz/vim-colorschemes'

[[plugins]]
repo = 'https://github.com/fuenor/jpmoveword.vim'

[[plugins]]
repo = 'https://github.com/mattn/sonictemplate-vim'

[[plugins]]
repo = 'https://github.com/tpope/vim-rhubarb'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'https://github.com/dense-analysis/ale'
hook_add = '''
source ~/.config/nvim/plugins/ale.vim
'''

[[plugins]]
repo = 'https://github.com/itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'https://github.com/jpalardy/vim-slime.git'
hook_add = '''
let g:slime_target = 'tmux'
let g:slime_default_config = {"socket_name": get(split($TMUX, ","), 0), "target_pane": ":.1"}
'''

[[plugins]]
repo = 'tikhomirov/vim-glsl'
