# ddc and its plugins
[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
call ddc#custom#patch_global('sources', ['file', 'nvim-lsp', 'around', 'ultisnips', 'buffer'])
set dictionary+=/usr/share/dict/words
call ddc#custom#set_context(["python", "c", "cpp", "[a-z, A-Z]+"], { ->
  \ ddc#syntax#in('Comment') || ddc#syntax#in('String') || ddc#syntax#in('rustCommentLineDoc') ? {
  \   'sources': ['file', 'dictionary', 'around', 'buffer'],
  \ } : {} })
call ddc#custom#patch_filetype(["text", "markdown", "gitcommit", 'tex'], 'sources', ['file', 'around', 'buffer', 'spell_user', 'dictionary'])
call ddc#custom#patch_global('sourceOptions', {
    \ 'file': { 'mark': 'F', 'forceCompletionPattern': '\S/\S*'},
    \ 'nvim-lsp': { 'mark':'lsp', 'forceCompletionPattern': '\.\w*|:\w*|->\w*'},
    \ 'around': { 'mark': 'A' },
    \ 'buffer': { 'mark': 'B' },
    \ 'ultisnips': { 'mark': 'US' },
    \ '_': { 'matchers': ['matcher_fuzzy'],
    \        'sorters':  ['sorter_rank'],
    \        'ignoreCase': v:true},
    \   })
call ddc#custom#patch_global('sourceParams', {
    \ 'nvim-lsp': { 'kindLabels': { 'Class': 'c' } },
    \ 'buffer': {'requireSameFiletype': v:false},
    \   })
call ddc#enable()
'''
[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
[[plugins]]
repo = 'matsui54/ddc-matcher_fuzzy'
[[plugins]]
repo = 'matsui54/ddc-ultisnips'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
[[plugins]]
repo = 'Shougo/ddc-around'
[[plugins]]
repo = 'matsui54/ddc-buffer'
[[plugins]]
repo = 'LumaKernel/ddc-file'
[[plugins]]
repo = 'matsui54/ddc-dictionary'
[[plugins]]
repo = '~/ghq/github.com/woodyZootopia/ddc-spell-user'

# LSP configuration
[[plugins]]
repo = 'neovim/nvim-lspconfig'
[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
[[plugins]]
repo = 'ray-x/lsp_signature.nvim'

# Ultisnip and snippet list
[[plugins]]
repo = 'Sirver/ultisnips'
hook_add = '''
" Trigger configuration. You need to change this to something else than <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
" let g:UltiSnipsJumpBackwardTrigger="<c-b>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
'''
[[plugins]]
repo = 'honza/vim-snippets'

# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
hook_install = '''
fzf#install()
'''
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
nnoremap <silent> <space>fr  <Cmd>History<CR>
nnoremap <silent> <space>ff  <Cmd>Files<CR>
nnoremap <silent> <space>fb  <Cmd>Buffers<CR>
nnoremap <silent> <space>fc  <Cmd>History:<CR>
" nnoremap <silent> <space>fgc  <Cmd>Commits<CR>
nnoremap <silent> <space>fm  <Cmd>Maps<CR>
nnoremap <silent> <space>fh  <Cmd>Helptags<CR>
nnoremap <silent> <space>ft  <Cmd>Tags<CR>
nnoremap <silent> <space>fg  <Cmd>Rg<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_preview_win_floating = 1
nmap <Leader>hs <Plug>(GitGutterStageHunk)
nmap <Leader>hu <Plug>(GitGutterUndoHunk)
nmap <Leader>hp <Plug>(GitGutterPreviewHunk)
nmap ]h         <Plug>(GitGutterNextHunk)
nmap [h         <Plug>(GitGutterPrevHunk)
omap ih         <Plug>(GitGutterTextObjectInnerPending)
omap ah         <Plug>(GitGutterTextObjectOuterPending)
xmap ih         <Plug>(GitGutterTextObjectInnerVisual)
xmap ah         <Plug>(GitGutterTextObjectOuterVisual)
nmap ]c         <Plug>(GitGutterNextHunk)
nmap [c         <Plug>(GitGutterPrevHunk)
omap ic         <Plug>(GitGutterTextObjectInnerPending)
omap ac         <Plug>(GitGutterTextObjectOuterPending)
xmap ic         <Plug>(GitGutterTextObjectInnerVisual)
xmap ac         <Plug>(GitGutterTextObjectOuterVisual)

nmap <Up> <Plug>(GitGutterStageHunk)
nmap <PageUp> <Plug>(GitGutterPrevHunk)<Plug>(GitGutterPreviewHunk)
nmap <PageDown> <Plug>(GitGutterNextHunk)<Plug>(GitGutterPreviewHunk)
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <leader>gs :Git <CR><C-w>T
nnoremap <leader>ga :Gwrite<CR>
nnoremap <leader>gc :Git commit -v<CR>
nnoremap <leader>gb :Git blame<CR>
nnoremap <leader>gh :tab sp<CR>:0Gclog<CR>
nnoremap <leader>gp :Dispatch! git push<CR>
nnoremap <leader>gf :Dispatch! git fetch<CR>
nnoremap <leader>gd :vert :Gdiffsplit<CR>
nnoremap <leader>gr :Git rebase -i<CR>
nnoremap <leader>gg :Glgrep ""<Left>
nnoremap <leader>gm :Git merge 

nnoremap <S-Up> :Gwrite<CR>
nnoremap <C-Up> :Git commit -v<CR>
nnoremap <expr> <Right> '<Cmd>' . (&diff ? 'only' : 'vert Gdiffsplit!') . '<CR>'
nnoremap <expr> <Left> '<Cmd>' . (&ft==#'fugitiveblame' ? 'quit' : 'Git blame') . '<CR>'
nnoremap <Down> :Dispatch! git fetch<CR>
nnoremap <C-Down> :Dispatch! git pull<CR>
'''

# indentline implementation in lua
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
nmap <leader>t :TagbarToggle<CR>
let g:tagbar_type_go = {
        \ 'ctagstype' : 'go',
        \ 'kinds'     : [
            \ 'p:package',
            \ 'i:imports:1',
            \ 'c:constants',
            \ 'v:variables',
            \ 't:types',
            \ 'n:interfaces',
            \ 'w:fields',
            \ 'e:embedded',
            \ 'm:methods',
            \ 'r:constructor',
            \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }

let g:tagbar_sort = 0
let g:tagbar_autoclose = 0
'''

[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
nnoremap U :UndotreeToggle<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
            \  'colorscheme': 'iceberg',
            \  'active': {
                \     'right' : [ [ 'lineinfo' ],
                \            [ 'percent', 'editdistance', 'fileencoding' ],
                \            [ 'fileformat', 'fileencoding', 'filetype' ] ]
                \ },
                \ 'component_function': {
                    \    'editdistance': 'NCCCachedEditDistance',
                    \}
                \}

"let g:lightline.separator = { 'left': "\ue0b8", 'right': "\ue0be" }
"let g:lightline.subseparator = { 'left':  "\ue0b9", 'right': "\ue0b9"  }
"let g:lightline.tabline_separator = { 'left': "\ue0bc", 'right': "\ue0ba" }
"let g:lightline.tabline_subseparator = { 'left': "\ue0bb", 'right': "\ue0bb" }
"let g:denops#debug=1
'''

[[plugins]]
repo = 'jpalardy/vim-slime'
hook_add = '''
nmap <c-c><c-c> <Plug>SlimeParagraphSend
nmap <c-c><c-n> <Plug>SlimeParagraphSend}/[^\n]<CR>
nmap <c-c><c-p> <Plug>SlimeParagraphSend{?[^\n]<CR>
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
hook_add = '''
let g:asyncrun_bell=1
let g:asyncrun_open = 8
'''

[[plugins]]
repo = '~/ghq/github.com/woodyZootopia/gitsession.vim'
hook_add = '''
let g:gitsession_autosave = 1
let g:gitsession_tmp_dir = g:nvim_home_directory .. '/tmp/gitsession'
'''

[[plugins]]
repo = 'LeafCage/vimhelpgenerator.git'

[[plugins]]
repo = 'tversteeg/registers.nvim'

# colorscheme
[[plugins]]
# repo = '~/ghq/github.com/woodyZootopia/iceberg.vim'
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'cocopon/pgmnt.vim'
[[plugins]]
repo = 'cocopon/inspecthi.vim'
[[plugins]]
repo = 'cocopon/colorswatch.vim'

[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'
hook_post_source = '''
let g:dps_ghosttext#ftmap['www.overleaf.com']='tex'
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = '0'
hook_post_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {
      'lua',
      'toml',
      'tex',
      'latex',
    }
  },
  indent = {
    enable = false
  },
  ensure_installed = {'c', 'cpp', 'python', 'rust', 'latex', 'vim'}
}
EOF
'''
hook_install = 'TSUpdate'
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'cohama/agit.vim'
hook_add = '''
nnoremap <leader>gl :Agit<CR>
'''

[[plugins]]
repo = 'voldikss/vim-floaterm.git'
hook_add = '''
let g:floaterm_width=0.9
let g:floaterm_height=0.9
nnoremap [Win]z <Cmd>FloatermToggle<CR>
tnoremap <silent> <C-[> <C-\><C-n>:FloatermToggle<CR>
tnoremap <silent> <C-l> <C-\><C-n>:FloatermToggle<CR>
'''

# [[plugins]]
# repo='~/ghq/github.com/woodyZootopia/novel-char-counter'
# hook_post_source='''
# augroup calc-novel-diff
#     autocmd!
#     autocmd BufReadPost,BufWritePost,InsertLeave *.txt call NCCUpdateEditDistance()
# augroup END

# '''
