[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
hook_post_source = '''
call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': 'latex'})
call lexima#add_rule({'char': '$', 'at': '\%#\$', 'leave': 1, 'filetype': 'latex'})
call lexima#add_rule({'char': '<BS>', 'at': '\$\%#\$', 'delete': 1, 'filetype': 'latex'})
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.config/nvim/plugins/defx.vim
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
source ~/.config/nvim/plugins/deol.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'Shougo/unite-outline'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/neoyank.vim'
[[plugins]]
repo = 'neoclide/denite-git'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_post_source='''
IndentLinesEnable
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add='''
source ~/.config/nvim/plugins/quickrun.vim
'''
[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'woodyZootopia/flatwhite-vim'

[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'
hook_add = '''
source ~/.config/nvim/plugins/textobj.vim
'''

[[plugins]]
repo = 'kana/vim-textobj-syntax'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/plugins/gitgutter.vim
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
source ~/.config/nvim/plugins/nerdcommenter.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
source ~/.config/nvim/plugins/tabular_easyalign.vim
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
nmap <space>b <Plug>(openbrowser-smart-search)
vmap <space>b <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'majutsushi/tagbar.git'
hook_add = '''
source ~/.config/nvim/plugins/tagbar.vim
'''

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo='t9md/vim-quickhl.git'
hook_add = '''
source ~/.config/nvim/plugins/quickhl.vim
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.config/nvim/plugins/languageclient.vim
'''

[[plugins]]
repo = 'Shougo/echodoc.vim'
hook_add = '''
source ~/.config/nvim/plugins/echodoc.vim
'''
