# vim-asterisk
# [[plugins]]
# repo = 'haya14busa/vim-asterisk'
# hook_add = 'call Asterisk_add()'

# operator argumentation
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'

# textobj argumentation
[[plugins]]
repo = 'kana/vim-textobj-user'
hook_add = 'call Textobjuser_add()'
[[plugins]]
repo = 'kana/vim-textobj-syntax'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'kana/vim-textobj-entire'
hook_add = 'call Textobjentire_add()'

# move words
[[plugins]]
repo = 'fuenor/jpmoveword.vim'
hook_add = '''
let g:jpmoveword_separator='，．、。・「」『』（）【】\\'
let g:matchpairs_textobject=1
'''

# colorscheme
[[plugins]]
repo = 'woodyZootopia/iceberg.vim'
[[plugins]]
repo = 'cocopon/pgmnt.vim'
# [[plugins]]
# repo = 'cocopon/colorswatch.vim'

[[plugins]]
repo = 'woodyZootopia/gitsession.vim'
hook_add = '''
let g:gitsession_autosave = 1
let g:gitsession_tmp_dir = g:nvim_conf_dir .. '/tmp/gitsession'
'''
[[plugins]]
repo = 'lewis6991/impatient.nvim'

[[plugins]]
repo = 'https://github.com/tyru/capture.vim'

[[plugins]]
repo = 'https://github.com/skanehira/preview-markdown.vim'
hook_add = 'let g:preview_markdown_auto_update=1'

[[plugins]]
repo = 'https://github.com/subnut/nvim-ghost.nvim'
hook_done_update = 'call nvim_ghost#installer#install()'
hook_add = '''
augroup nvim_ghost_user_autocommands
  au User www.reddit.com,www.stackoverflow.com,github.com set filetype=markdown
  au User www.overleaf.com set filetype=tex
augroup END
'''
