[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
source ~/.config/nvim/plugins/lexima.vim
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
source ~/.config/nvim/plugins/easymotion.vim
'''


[[plugins]]
repo = 'https://github.com/fatih/vim-go'
on_ft = ['go']
hook_add = '''
source ~/.config/nvim/plugins/vim-go.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'https://github.com/ElmCast/elm-vim'
hook_source = '''
source ~/.config/nvim/plugins/elm.vim
'''
on_ft = ['elm']
