[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_leader_key=','
'''
on_ft = ['html', 'xml', 'vue', 'htmldjango']
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = 'call Vimtex_add()'
[[plugins]]
repo = 'AtsushiM/search-parent.vim'
on_ft = ['sass','scss','css']
[[plugins]]
repo = 'akiyan/vim-textobj-php'
on_ft = ['html','htm']
[[plugins]]
repo = 'tpope/vim-surround'
on_ft = ['html','htm']
[[plugins]]
repo = 'wokalski/autocomplete-flow'
on_ft = ['html', 'htm', 'js']
[[plugins]]
repo = 'zeekay/vim-beautify'
on_ft = ['html', 'htm', 'js']
[[plugins]]
repo = 'AtsushiM/sass-compile.vim'
on_ft = ['sass','scss']
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_folding_disabled = 1
'''
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['lisp']

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'hrsh7th/cmp-path'
[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
[[plugins]]
repo = 'quangnguyen30192/cmp-nvim-ultisnips'
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['nvim-lspconfig', 'cmp-nvim-lsp', 'cmp-buffer', 'cmp-path', 'cmp-cmdline', 'cmp-nvim-ultisnips' ]
on_event = ['InsertEnter', 'CmdlineEnter']
hook_post_source = 'call Nvim_cmp_postsource()'

# align
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga  <Plug>(EasyAlign)
'''
on_map = '<Plug>(EasyAlign)'

# paren closing completion
[[plugins]]
repo = 'kana/vim-smartinput'
on_event = 'InsertEnter'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_ft = ['css', 'vim', 'markdown']
hook_post_source = '''
luado require 'colorizer'.setup()
ColorizerAttachToBuffer " Attach to the current buffer
'''

# LSP configuration
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_ft = ['c', 'cpp', 'rust', 'python', 'vim', 'tex', 'javascript', 'typescript']
depends = 'lsp_signature.nvim'
hook_post_source = '''
if !exists('g:vscode')
    exe 'source' g:nvim_home_directory .. 'rcs/lsp.vim'
endif
LspStart
'''
[[plugins]]
repo = 'ray-x/lsp_signature.nvim'

[[plugins]]
repo = 'tpope/vim-dispatch'
on_map = '<Cmd>Dispatch!'

[[plugins]]
repo = 'bps/vim-textobj-python'
hook_add = '''
let g:textobj_python_no_default_key_mappings = 1
'''
hook_post_source = 'call Textobjpython_postsource()'
on_ft = 'python'


[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript']
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'
