
on_event = 'InsertEnter'
depends = ['neosnippet-snippets']





#ここを参考https://qiita.com/alpaca_taichou/items/056a4c42fe7a928973e6


hook_add = '''
 let g:sass_compile_auto                 = 1
 let g:sass_compile_cdloop               = 5
 let g:sass_compile_cssdir               = ['css', 'stylesheet']
 let g:sass_compile_file                 = ['scss', 'sass']
 let g:sass_started_dirs                 = []
 let g:sass_compile_beforecmd            = ''
 autocmd FileType less,sass  setlocal sw = 2 sts=2 ts=2 et
'''
depends = ['search-parent']

