[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add='''
nnoremap <silent> <space>fr :<C-u>Denite file_mru<CR>
nnoremap <silent> <space>fb :<C-u>Denite buffer<CR>
nnoremap <silent> <space>fy :<C-u>Denite neoyank<CR>
nnoremap <silent> <space>ff :<C-u>Denite file_rec<CR>
nnoremap <silent> <space>fu :<C-u>Denite outline<CR>
'''
[[plugins]]
repo = 'Shougo/unite-outline'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_post_source='''
IndentLinesEnable
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-syntax'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add='''
let g:NERDSpaceDelims=1
let g:NERDDefaultAlign='left'
let g:NERDCustomDelimiters = {'vim': {'left': '"','right':''}}
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'godlygeek/tabular'
hook_add = '''
xmap <Space>ga :Tabular 
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
nmap <space>b <Plug>(openbrowser-smart-search)
vmap <space>b <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
