[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_leader_key=','
'''
on_ft = ['html', 'xml', 'vue', 'htmldjango']
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = 'call Vimtex_add()'
[[plugins]]
repo = 'AtsushiM/search-parent.vim'
on_ft = ['sass','scss','css']
[[plugins]]
repo = 'akiyan/vim-textobj-php'
on_ft = ['html','htm']
[[plugins]]
repo = 'tpope/vim-surround'
on_ft = ['html','htm']
[[plugins]]
repo = 'wokalski/autocomplete-flow'
on_ft = ['html', 'htm', 'js']
[[plugins]]
repo = 'zeekay/vim-beautify'
on_ft = ['html', 'htm', 'js']
[[plugins]]
repo = 'AtsushiM/sass-compile.vim'
on_ft = ['sass','scss']
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_folding_disabled = 1
'''
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['lisp']

# ddc and its plugins
[[plugins]]
repo = 'Shougo/ddc.vim'
hook_post_source = 'call Ddc_add()'
on_event = 'InsertEnter'
depends = ['ddc-nvim-lsp', 'ddc-matcher_fuzzy', 'ddc-ultisnips', 'ddc-sorter_rank', 'ddc-around', 'ddc-buffer', 'ddc-file', 'ddc-dictionary']

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
[[plugins]]
repo = 'matsui54/ddc-matcher_fuzzy'
[[plugins]]
repo = 'matsui54/ddc-ultisnips'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
[[plugins]]
repo = 'Shougo/ddc-around'
[[plugins]]
repo = 'matsui54/ddc-buffer'
[[plugins]]
repo = 'LumaKernel/ddc-file'
[[plugins]]
repo = 'matsui54/ddc-dictionary'
# [[plugins]]
# repo = '~/ghq/github.com/woodyZootopia/ddc-spell-user'

