[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_leader_key=','
'''
on_ft = ['html', 'xml', 'vue', 'htmldjango']
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = 'call Vimtex_add()'
[[plugins]]
repo = 'AtsushiM/search-parent.vim'
on_ft = ['sass','scss','css']
[[plugins]]
repo = 'akiyan/vim-textobj-php'
on_ft = ['html','htm']
[[plugins]]
repo = 'tpope/vim-surround'
on_ft = ['html','htm']
[[plugins]]
repo = 'wokalski/autocomplete-flow'
on_ft = ['html', 'htm', 'js']
[[plugins]]
repo = 'zeekay/vim-beautify'
on_ft = ['html', 'htm', 'js']
[[plugins]]
repo = 'AtsushiM/sass-compile.vim'
on_ft = ['sass','scss']
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_folding_disabled = 1
'''
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['lisp']

[[plugins]]
repo = 'hrsh7th/cmp-look'
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'hrsh7th/cmp-path'
[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
[[plugins]]
repo = 'saadparwaiz1/cmp_luasnip'
[[plugins]]
repo = 'onsails/lspkind.nvim'
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['nvim-lspconfig', 'cmp-nvim-lsp', 'cmp-buffer', 'cmp-path', 'cmp-cmdline', 'cmp_luasnip', 'lspkind.nvim', 'cmp-look']
on_event = ['InsertEnter', 'CmdlineEnter']
on_ft = ['python', 'rust', 'lua', 'vim']
hook_post_source = '''
exe 'source' $HOME . '/.config/nvim/toml/nvim-cmp.lua'
'''

[[plugins]]
repo =  'kyazdani42/nvim-tree.lua'
hook_add = '''
nmap <silent> <leader>d :<C-u>exe 'lcd' expand('%:p:h')<CR><Cmd>NvimTreeToggle<CR>
nmap <silent> <Plug>(my-win)t    :<C-u>tab sp<CR><leader>d
nmap <silent> <leader>n <Cmd>NvimTreeFocus<CR>
'''
hook_post_source = '''
exe 'source' $HOME . '/.config/nvim/toml/nvim-tree.lua'
'''
on_map = ['<Cmd>NvimTreeToggle', '<Cmd>NvimTreeFocus']


# align
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga  <Plug>(EasyAlign)
'''
on_map = '<Plug>(EasyAlign)'

# paren closing completion
[[plugins]]
repo = 'kana/vim-smartinput'
on_event = 'InsertEnter'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_ft = ['css', 'vim', 'markdown']
hook_post_source = '''
luado require 'colorizer'.setup()
ColorizerAttachToBuffer " Attach to the current buffer
'''

[[plugins]]
repo = 'tpope/vim-dispatch'
on_map = '<Cmd>Dispatch!'

[[plugins]]
repo = 'bps/vim-textobj-python'
hook_add = '''
let g:textobj_python_no_default_key_mappings = 1
'''
hook_post_source = 'call Textobjpython_postsource()'
on_ft = 'python'


[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript']
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'
