# denops!
[[plugins]]
repo = 'vim-denops/denops.vim'

# vim-asterisk
[[plugins]]
repo = 'haya14busa/vim-asterisk'
hook_add = '''
map *   <Plug>(asterisk-*)
map #   <Plug>(asterisk-#)
map g*  <Plug>(asterisk-g*)
map g#  <Plug>(asterisk-g#)
map z*  <Plug>(asterisk-z*)
map gz* <Plug>(asterisk-gz*)
map z#  <Plug>(asterisk-z#)
map gz# <Plug>(asterisk-gz#)
let g:asterisk#keeppos = 1
'''

# paren closing completion
[[plugins]]
repo = 'kana/vim-smartinput'

# operator argumentation
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'

# textobj argumentation
[[plugins]]
repo = 'kana/vim-textobj-user'
hook_add = '''
" operator mappings
map        <silent>sa             <Plug>(operator-surround-append)
map        <silent>sd             <Plug>(operator-surround-delete)
map        <silent>sr             <Plug>(operator-surround-replace)
omap       ab                     <Plug>(textobj-multiblock-a)
omap       ib                     <Plug>(textobj-multiblock-i)
vmap       ab                     <Plug>(textobj-multiblock-a)
vmap       ib                     <Plug>(textobj-multiblock-i)

" if you use vim-textobj-multiblock
nmap <silent>sdd <Plug>(operator-surround-delete)<Plug>(textobj-multiblock-a)
nmap <silent>srr <Plug>(operator-surround-replace)<Plug>(textobj-multiblock-a)

" if you use vim-textobj-between
nmap <silent>sdb <Plug>(operator-surround-delete)<Plug>(textobj-between-a)
nmap <silent>srb <Plug>(operator-surround-replace)<Plug>(textobj-between-a)
'''
[[plugins]]
repo = 'kana/vim-textobj-syntax'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'kana/vim-textobj-entire'
hook_add = '''
let g:textobj_entire_no_default_key_mappings = 1
omap av <Plug>(textobj-entire-a)
omap iv <Plug>(textobj-entire-i)
xmap av <Plug>(textobj-entire-a)
xmap iv <Plug>(textobj-entire-i)
'''

# commenter
[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims=1
let g:NERDDefaultAlign='left'
let g:NERDCustomDelimiters = {'vim': {'left': '"','right':''}}
noremap <C-_> <Plug>NERDCommenterToggle
'''

# align
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga  <Plug>(EasyAlign)
'''

# move words
[[plugins]]
repo = 'fuenor/jpmoveword.vim'
hook_add = '''
let g:jpmoveword_separator='，．、。・「」『』（）【】\\'
let g:matchpairs_textobject=1
'''

# :Gbrowse to open github
[[plugins]]
repo = 'tpope/vim-rhubarb'

# :SpellCheck to put spell errors to quickfix
# [[plugins]]
# repo = 'https://github.com/inkarkat/vim-SpellCheck'
# [[plugins]]
# repo = 'https://github.com/inkarkat/vim-ingo-library'

# :HelpfulVersion to view version
# [[plugins]]
# repo = 'tweekmonster/helpful.vim'

# misc
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
# [[plugins]]
# repo = 'tikhomirov/vim-glsl'

# :Dispatch to run asynchronously
[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'ap/vim-css-color'
# [[plugins]]
# repo = 'hail2u/vim-css3-syntax'
# [[plugins]]
# repo = 'pangloss/vim-javascript'
# [[plugins]]
# repo = 'kchmck/vim-coffee-script'
# [[plugins]]
# repo = 'hynek/vim-python-pep8-indent'
# [[plugins]]
# repo = 'jceb/vim-orgmode'
# [[plugins]]
# repo = 'qnighy/satysfi.vim'
# [[plugins]]
# repo = 'cakebaker/scss-syntax.vim'
[[plugins]]
repo = 'bps/vim-textobj-python'
hook_add = '''
let g:textobj_python_no_default_key_mappings = 1
'''
hook_post_source = '''
call textobj#user#map('python', {
      \   'class': {
      \     'select-a': '<buffer>ax',
      \     'select-i': '<buffer>ix',
      \     'move-n': '<buffer>]x',
      \     'move-p': '<buffer>[x',
      \   },
      \   'function': {
      \     'select-a': '<buffer>af',
      \     'select-i': '<buffer>if',
      \     'move-n': '<buffer>]f',
      \     'move-p': '<buffer>[f',
      \   }
      \ })
'''

[[plugins]]
repo = 'mhinz/vim-sayonara.git'

[[plugins]]
repo =  'kyazdani42/nvim-tree.lua'
hook_add = '''
exe 'source' expand('~/.config/nvim/toml/nvim-tree.lua')
nnoremap <silent> [Win]t    :<C-u>tab sp<CR>:exe 'lcd' expand('%:p:h')<CR>:NvimTreeToggle<CR>
nnoremap <silent> <leader>d :<C-u>exe 'lcd' expand('%:p:h')<CR>:NvimTreeToggle<CR>
nnoremap <silent> <leader>n :<C-u>exe 'lcd' expand('%:p:h')<CR>:NvimTreeFocus<CR>
'''
