# vim-asterisk
# [[plugins]]
# repo = 'haya14busa/vim-asterisk'
# hook_add = 'call Asterisk_add()'

# operator argumentation
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'

# textobj argumentation
[[plugins]]
repo = 'kana/vim-textobj-user'
hook_add = 'call Textobjuser_add()'
[[plugins]]
repo = 'kana/vim-textobj-syntax'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'kana/vim-textobj-entire'
hook_add = 'call Textobjentire_add()'

# move words
[[plugins]]
repo = 'fuenor/jpmoveword.vim'
hook_add = '''
let g:jpmoveword_separator='，．、。・「」『』（）【】\\'
let g:matchpairs_textobject=1
'''

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
# [[plugins]]
# repo = 'cocopon/pgmnt.vim'
# [[plugins]]
# repo = 'cocopon/inspecthi.vim'
# [[plugins]]
# repo = 'cocopon/colorswatch.vim'

[[plugins]]
repo = 'woodyZootopia/gitsession.vim'
hook_add = '''
let g:gitsession_autosave = 1
let g:gitsession_tmp_dir = g:nvim_home_directory .. '/tmp/gitsession'
'''
[[plugins]]
repo = 'lewis6991/impatient.nvim'
