[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'kat0h/bufpreview.vim'
on_ft = 'markdown'
build = 'deno task prepare'
hook_add = '''
augroup markdown_bufpreview
  autocmd!
  autocmd FileType markdown nnoremap <buffer> <F5> <Cmd>PreviewMarkdown<CR>
  autocmd FileType markdown inoremap <buffer> <F5> <Cmd>PreviewMarkdown<CR>
augroup END
'''
depends = 'denops.vim'
