[[plugins]]
repo = 'https://github.com/lambdalisue/fern.vim'
hook_add = '''
nnoremap <leader>d <Cmd>Fern %:h<CR>
nnoremap <leader>n <Cmd>Fern . -reveal=% -drawer<CR>
nnoremap st :<C-u>tab sp<CR><Cmd>Fern %:h<CR>
'''
hook_source='''
function! s:init_fern() abort
  silent! nunmap <buffer> s
  silent! nunmap <buffer> N
  nmap <buffer> o <Plug>(fern-action-open-or-expand)
  nmap <buffer> l <Plug>(fern-action-open-or-expand)
  nmap <buffer> <C-v> <Plug>(fern-action-open:vsplit)<C-w>p
  nmap <buffer> <C-s> <Plug>(fern-action-open:split)<C-w>p
  nmap <buffer> <C-t> <Plug>(fern-action-open:tabedit)
  nmap <buffer> h <Plug>(fern-action-collapse)
  nmap <buffer> <CR> <Plug>(fern-action-tcd)<Plug>(fern-action-open-or-enter)
  nmap <buffer> - <Plug>(fern-action-leave)<Plug>(fern-wait)<Plug>(fern-action-tcd:root)
  nmap <buffer> L <Plug>(fern-action-new-file)
  nmap <buffer> d <Plug>(fern-action-trash)<CR>
  nmap <buffer> D <Plug>(fern-action-trash=)y<CR>
endfunction

augroup fern-custom
  autocmd!
  autocmd FileType fern call s:init_fern()
  autocmd FileType fern call glyph_palette#apply()
augroup END
'''
depends = ['fern-renderer-nerdfont.vim', 'glyph-palette.vim', 'fern-git-status.vim', 'fern-hijack.vim']

[[plugins]]
repo = 'https://github.com/lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
let g:fern#renderer = "nerdfont"
'''
depends = ['nerdfont.vim', 'nvim-web-devicons']
[[plugins]]
repo = 'https://github.com/lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'https://github.com/lambdalisue/glyph-palette.vim'
[[plugins]]
repo = 'https://github.com/lambdalisue/fern-git-status.vim'
[[plugins]]
repo = 'https://github.com/lambdalisue/fern-hijack.vim'
